export const venezuelaZones = [
  "Distrito Capital, Municipio Libertador",
  "Distrito Capital, 23 de Enero",
  "Distrito Capital, Altamira",
  "Distrito Capital, Antimano",
  "Distrito Capital, Bellas Artes",
  "Distrito Capital, Candelaria",
  "Distrito Capital, Caricuao",
  "Distrito Capital, Catia",
  "Distrito Capital, El Paraiso",
  "Distrito Capital, El Recreo",
  "Distrito Capital, La Florida",
  "Distrito Capital, La Pastora",
  "Distrito Capital, La Vega",
  "Distrito Capital, Los Chaguaramos",
  "Distrito Capital, Montalban",
  "Distrito Capital, Propatria",
  "Distrito Capital, San Bernardino",
  "Distrito Capital, San Jose",
  "Distrito Capital, San Juan",
  "Distrito Capital, Santa Monica",
  "Distrito Capital, Sabana Grande",
  "Miranda, Municipio Baruta",
  "Miranda, Municipio Chacao",
  "Miranda, Municipio El Hatillo",
  "Miranda, Municipio Sucre",
  "Miranda, Municipio Guaicaipuro",
  "Miranda, Municipio Los Salias",
  "Miranda, Municipio Carrizal",
  "Miranda, Municipio Plaza",
  "Miranda, Municipio Zamora",
  "Miranda, Municipio Acevedo",
  "Miranda, Municipio Andres Bello",
  "Miranda, Municipio Brión",
  "Miranda, Municipio Buroz",
  "Miranda, Municipio Cristóbal Rojas",
  "Miranda, Municipio Independencia",
  "Miranda, Municipio Lander",
  "Miranda, Municipio Paz Castillo",
  "Miranda, Municipio Simón Bolívar",
  "Miranda, Municipio Urdaneta",
  "Miranda, Baruta",
  "Miranda, Chacao",
  "Miranda, El Hatillo",
  "Miranda, Petare",
  "Miranda, Los Dos Caminos",
  "Miranda, La Urbina",
  "Miranda, Palo Verde",
  "Miranda, Macaracuay",
  "Miranda, Los Palos Grandes",
  "Miranda, La California",
  "Miranda, Guarenas",
  "Miranda, Guatire",
  "Miranda, Los Teques",
  "Miranda, San Antonio de los Altos",
  "Miranda, Carrizal",
  "Miranda, Charallave",
  "Miranda, Ocumare del Tuy",
  "Miranda, Santa Teresa del Tuy",
  "Miranda, Santa Lucia",
  "Miranda, Cua",
  "La Guaira, Municipio Vargas",
  "La Guaira, La Guaira",
  "La Guaira, Maiquetia",
  "La Guaira, Catia La Mar",
  "La Guaira, Macuto",
  "La Guaira, Caraballeda",
  "La Guaira, Naiguata",
  "La Guaira, Carayaca",
  "La Guaira, Caruao",
  "La Guaira, El Junko",
  "La Guaira, Urimare",
  "Aragua, Municipio Girardot",
  "Aragua, Municipio Mario Briceño Iragorry",
  "Aragua, Municipio Santiago Mariño",
  "Aragua, Municipio Francisco Linares Alcántara",
  "Aragua, Municipio Sucre",
  "Aragua, Municipio José Félix Ribas",
  "Aragua, Municipio Libertador",
  "Aragua, Municipio Zamora",
  "Aragua, Maracay",
  "Aragua, El Limon",
  "Aragua, Cagua",
  "Aragua, Turmero",
  "Aragua, La Victoria",
  "Aragua, San Mateo",
  "Aragua, Palo Negro",
  "Aragua, Villa de Cura",
  "Carabobo, Municipio Valencia",
  "Carabobo, Municipio Naguanagua",
  "Carabobo, Municipio San Diego",
  "Carabobo, Municipio Libertador",
  "Carabobo, Municipio Los Guayos",
  "Carabobo, Municipio Guacara",
  "Carabobo, Municipio Puerto Cabello",
  "Carabobo, Municipio Juan José Mora",
  "Carabobo, Valencia",
  "Carabobo, Naguanagua",
  "Carabobo, San Diego",
  "Carabobo, Guacara",
  "Carabobo, Los Guayos",
  "Carabobo, Tocuyito",
  "Carabobo, Puerto Cabello",
  "Anzoategui, Municipio Simón Bolívar",
  "Anzoategui, Municipio Juan Antonio Sotillo",
  "Anzoategui, Municipio Urbaneja",
  "Anzoategui, Municipio Guanta",
  "Anzoategui, Municipio Anaco",
  "Anzoategui, Municipio Freites",
  "Anzoategui, Barcelona",
  "Anzoategui, Puerto La Cruz",
  "Anzoategui, Lecheria",
  "Anzoategui, Guanta",
  "Anzoategui, Anaco",
  "Lara, Municipio Iribarren",
  "Lara, Municipio Palavecino",
  "Lara, Municipio Torres",
  "Lara, Municipio Jiménez",
  "Lara, Municipio Morán",
  "Lara, Barquisimeto",
  "Lara, Cabudare",
  "Lara, Carora",
  "Zulia, Municipio Maracaibo",
  "Zulia, Municipio San Francisco",
  "Zulia, Municipio Cabimas",
  "Zulia, Municipio Lagunillas",
  "Zulia, Municipio Mara",
  "Zulia, Maracaibo",
  "Zulia, San Francisco",
  "Zulia, Cabimas",
  "Mérida, Municipio Libertador",
  "Mérida, Municipio Campo Elías",
  "Mérida, Municipio Sucre",
  "Mérida, Merida",
  "Mérida, Ejido",
  "Táchira, Municipio San Cristóbal",
  "Táchira, Municipio Cárdenas",
  "Táchira, Municipio Junín",
  "Táchira, San Cristobal",
  "Táchira, Tariba",
  "Nueva Esparta, Municipio Mariño",
  "Nueva Esparta, Municipio Maneiro",
  "Nueva Esparta, Municipio García",
  "Nueva Esparta, Porlamar",
  "Nueva Esparta, Pampatar",
  "Bolívar, Municipio Caroní",
  "Bolívar, Municipio Angostura del Orinoco",
  "Bolívar, Puerto Ordaz",
  "Bolívar, San Felix",
  "Bolívar, Ciudad Bolivar",
  "Falcón, Municipio Miranda",
  "Falcón, Municipio Carirubana",
  "Falcón, Coro",
  "Falcón, Punto Fijo",
  "Monagas, Municipio Maturín",
  "Monagas, Maturin",
  "Portuguesa, Municipio Guanare",
  "Portuguesa, Municipio Páez",
  "Portuguesa, Guanare",
  "Portuguesa, Acarigua",
  "Sucre, Municipio Sucre",
  "Sucre, Municipio Bermúdez",
  "Sucre, Cumana",
  "Sucre, Carupano",
  "Trujillo, Municipio Valera",
  "Trujillo, Municipio Trujillo",
  "Trujillo, Valera",
  "Yaracuy, Municipio San Felipe",
  "Yaracuy, Municipio Independencia",
  "Yaracuy, San Felipe",
  "Cojedes, Municipio Ezequiel Zamora",
  "Cojedes, San Carlos",
  "Guárico, Municipio Juan Germán Roscio",
  "Guárico, San Juan de los Morros",
  "Apure, Municipio San Fernando",
  "Apure, San Fernando de Apure",
  "Barinas, Municipio Barinas",
  "Barinas, Barinas",
  "Delta Amacuro, Municipio Tucupita",
  "Delta Amacuro, Tucupita",
  "Amazonas, Municipio Atures",
  "Amazonas, Puerto Ayacucho",
].sort((a, b) => a.localeCompare(b, "es"));
