CREATE TABLE IF NOT EXISTS personas (
  id TEXT PRIMARY KEY,
  pfif_person_id TEXT UNIQUE,
  origen TEXT NOT NULL DEFAULT 'web_form',
  url_origen TEXT,
  creado_en INTEGER NOT NULL,
  actualizado_en INTEGER NOT NULL,
  expira_en INTEGER,
  nombre_reportante TEXT,
  contacto_reportante TEXT,
  relacion_reportante TEXT,
  cedula_identidad INTEGER,
  nombre_completo TEXT NOT NULL,
  nombres_alternativos TEXT,
  sexo TEXT,
  edad_estimada INTEGER,
  fecha_nacimiento TEXT,
  descripcion_fisica TEXT,
  descripcion_vestimenta TEXT,
  url_foto TEXT,
  ultima_direccion_conocida TEXT,
  zona_ubicacion TEXT,
  ubicacion_normalizada TEXT,
  latitud_visto_ultima_vez REAL,
  longitud_visto_ultima_vez REAL,
  fecha_visto_ultima_vez INTEGER,
  contexto_visto_ultima_vez TEXT,
  estado_actual TEXT NOT NULL DEFAULT 'desaparecido',
  encontrado_en INTEGER,
  direccion_encontrado TEXT,
  latitud_encontrado REAL,
  longitud_encontrado REAL,
  notas_hallazgo TEXT,
  verificado INTEGER DEFAULT 0,
  verificado_por TEXT,
  fecha_verificacion INTEGER,
  spam INTEGER DEFAULT 0,
  duplicado_de TEXT,
  posible_duplicado_de TEXT,
  esta_eliminado INTEGER DEFAULT 0,
  eliminado_por TEXT,
  fecha_eliminacion INTEGER,
  motivo_eliminacion TEXT,
  localizado_por TEXT,
  localizado_contacto TEXT,
  localizado_relacion TEXT,
  localizado_nota TEXT,
  fecha_desaparicion TEXT,
  cantidad_reportes INTEGER DEFAULT 0,
  ha_sido_reportada_oficialmente INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS notas_persona (
  id TEXT PRIMARY KEY,
  persona_id TEXT NOT NULL REFERENCES personas(id),
  creado_en INTEGER NOT NULL,
  origen TEXT NOT NULL DEFAULT 'web_form',
  nombre_autor TEXT,
  contacto_autor TEXT,
  rol_autor TEXT,
  estado_nota TEXT,
  texto TEXT NOT NULL,
  url_foto TEXT,
  direccion_ubicacion TEXT,
  latitud_ubicacion REAL,
  longitud_ubicacion REAL,
  encontrado INTEGER DEFAULT 0,
  contacto_si_es_encontrado TEXT
);

CREATE TABLE IF NOT EXISTS zonas_rescate (
  id TEXT PRIMARY KEY,
  creado_en INTEGER NOT NULL,
  actualizado_en INTEGER NOT NULL,
  origen TEXT NOT NULL DEFAULT 'web_form',
  nombre_reportante TEXT,
  contacto_reportante TEXT,
  rol_reportante TEXT,
  titulo TEXT NOT NULL,
  descripcion TEXT,
  tipo_zona TEXT NOT NULL,
  direccion TEXT,
  latitud REAL NOT NULL,
  longitud REAL NOT NULL,
  radio_metros INTEGER DEFAULT 50,
  notas_ubicacion TEXT,
  urgencia TEXT NOT NULL DEFAULT 'alta',
  estado TEXT NOT NULL DEFAULT 'reportado',
  atrapados_estimados INTEGER,
  atrapados_confirmados INTEGER,
  rescatados_confirmados INTEGER,
  fallecidos_confirmados INTEGER,
  requiere_maquinaria_pesada INTEGER DEFAULT 0,
  requiere_unidad_canina INTEGER DEFAULT 0,
  requiere_atencion_medica INTEGER DEFAULT 0,
  requiere_apoyo_estructural INTEGER DEFAULT 0,
  requiere_tipo_sangre TEXT,
  necesidades_especificas TEXT,
  urls_fotos TEXT,
  verificado INTEGER DEFAULT 0,
  verificado_por TEXT,
  fecha_verificacion INTEGER,
  spam INTEGER DEFAULT 0,
  duplicado_de TEXT,
  resuelto_en INTEGER,
  notas_resolucion TEXT,
  esta_eliminado INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS solicitudes_ayuda (
  id TEXT PRIMARY KEY,
  creado_en INTEGER NOT NULL,
  actualizado_en INTEGER NOT NULL,
  origen TEXT NOT NULL DEFAULT 'web_form',
  tipo_solicitud TEXT NOT NULL,
  urgencia TEXT NOT NULL DEFAULT 'alta',
  urgencia_ia TEXT,
  titulo TEXT,
  descripcion TEXT NOT NULL,
  direccion TEXT,
  latitud REAL,
  longitud REAL,
  notas_ubicacion TEXT,
  nombre_solicitante TEXT,
  contacto_solicitante TEXT NOT NULL,
  para_quien TEXT DEFAULT 'si_mismo',
  cantidad_personas INTEGER DEFAULT 1,
  tiene_ninos INTEGER DEFAULT 0,
  tiene_ancianos INTEGER DEFAULT 0,
  tiene_discapacitados INTEGER DEFAULT 0,
  tiene_bebes INTEGER DEFAULT 0,
  datos_especificos TEXT,
  zona_vinculada_id TEXT REFERENCES zonas_rescate(id),
  persona_vinculada_id TEXT REFERENCES personas(id),
  estado TEXT NOT NULL DEFAULT 'abierta',
  asignado_a TEXT,
  id_asignado TEXT,
  asignado_en INTEGER,
  completado_en INTEGER,
  notas_cumplimiento TEXT,
  verificado INTEGER DEFAULT 0,
  spam INTEGER DEFAULT 0,
  duplicado_de TEXT,
  esta_eliminado INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS voluntarios (
  id TEXT PRIMARY KEY,
  registrado_en INTEGER NOT NULL,
  actualizado_en INTEGER NOT NULL,
  nombre TEXT NOT NULL,
  contacto TEXT NOT NULL,
  correo TEXT,
  pais TEXT NOT NULL DEFAULT 'VE',
  ciudad TEXT,
  tipo_voluntario TEXT NOT NULL DEFAULT 'ciudadano',
  habilidades TEXT,
  certificaciones TEXT,
  tiene_vehiculo INTEGER DEFAULT 0,
  tipo_vehiculo TEXT,
  capacidad_vehiculo INTEGER,
  equipamiento TEXT,
  nombre_organizacion TEXT,
  tipo_organizacion TEXT,
  contacto_organizacion TEXT,
  disponible_desde INTEGER,
  disponible_hasta INTEGER,
  notas TEXT,
  verificado INTEGER DEFAULT 0,
  activo INTEGER DEFAULT 1,
  fecha_ultima_vez_visto INTEGER,
  esta_eliminado INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS asistencias_voluntario (
  id TEXT PRIMARY KEY,
  voluntario_id TEXT NOT NULL REFERENCES voluntarios(id),
  fecha_entrada INTEGER NOT NULL,
  fecha_salida INTEGER,
  latitud REAL NOT NULL,
  longitud REAL NOT NULL,
  precision_metros INTEGER,
  direccion TEXT,
  zona_id TEXT REFERENCES zonas_rescate(id),
  nombre_zona TEXT,
  estado_asistencia TEXT NOT NULL DEFAULT 'disponible',
  notas TEXT
);

CREATE TABLE IF NOT EXISTS señales_caso (
  id TEXT PRIMARY KEY,
  creado_en INTEGER NOT NULL,
  tipo_entidad TEXT NOT NULL,
  entidad_id TEXT NOT NULL,
  tipo_señal TEXT NOT NULL,
  hash_contacto TEXT,
  hash_ip TEXT,
  nota TEXT
);

CREATE TABLE IF NOT EXISTS bitacora_moderacion (
  id TEXT PRIMARY KEY,
  creado_en INTEGER NOT NULL,
  moderador_id TEXT,
  nombre_moderador TEXT,
  accion TEXT NOT NULL,
  tipo_entidad TEXT NOT NULL,
  entidad_id TEXT NOT NULL,
  motivo TEXT,
  metadatos TEXT
);

CREATE TABLE IF NOT EXISTS reportes_mascotas (
  id TEXT PRIMARY KEY,
  creado_en INTEGER NOT NULL,
  actualizado_en INTEGER NOT NULL,
  tipo_reporte TEXT NOT NULL,
  nombre_mascota TEXT,
  tipo_mascota TEXT NOT NULL,
  estado TEXT,
  descripcion TEXT NOT NULL,
  zona TEXT NOT NULL,
  nombre_contacto TEXT,
  telefono_contacto TEXT NOT NULL,
  puede_acoger INTEGER DEFAULT 0,
  url_foto TEXT,
  verificado INTEGER DEFAULT 0,
  duplicado_de TEXT,
  esta_eliminado INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS reportes_refugios (
  id TEXT PRIMARY KEY,
  creado_en INTEGER NOT NULL,
  actualizado_en INTEGER NOT NULL,
  tipo_reporte TEXT NOT NULL,
  titulo TEXT NOT NULL,
  tipo_refugio TEXT,
  zona TEXT NOT NULL,
  nombre_contacto TEXT,
  telefono_contacto TEXT NOT NULL,
  capacidad INTEGER,
  tamano_grupo INTEGER,
  necesidades TEXT,
  descripcion TEXT NOT NULL,
  verificado INTEGER DEFAULT 0,
  duplicado_de TEXT,
  esta_eliminado INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS listas_hospital (
  id TEXT PRIMARY KEY,
  creado_en INTEGER NOT NULL,
  tipo_origen TEXT NOT NULL,
  url_origen TEXT,
  nombre_hospital TEXT NOT NULL,
  fecha_lista TEXT,
  estado TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS elementos_lista_hospital (
  id TEXT PRIMARY KEY,
  lista_id TEXT NOT NULL REFERENCES listas_hospital(id),
  creado_en INTEGER NOT NULL,
  nombre_completo TEXT NOT NULL,
  cedula_identidad INTEGER,
  edad_estimada INTEGER,
  estado TEXT,
  estado_coincidencia TEXT,
  persona_id_coincidente TEXT REFERENCES personas(id)
);
