CREATE TABLE IF NOT EXISTS persons (
  id TEXT PRIMARY KEY,
  pfif_person_id TEXT UNIQUE,
  source TEXT NOT NULL DEFAULT 'web_form',
  source_url TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  expires_at INTEGER,
  author_name TEXT,
  author_contact TEXT,
  author_relation TEXT,
  full_name TEXT NOT NULL,
  alternate_names TEXT,
  sex TEXT,
  age_estimated INTEGER,
  date_of_birth TEXT,
  physical_desc TEXT,
  clothing_desc TEXT,
  photo_url TEXT,
  last_seen_address TEXT,
  location_zone TEXT,
  location_normalized TEXT,
  last_seen_lat REAL,
  last_seen_lng REAL,
  last_seen_at INTEGER,
  last_seen_context TEXT,
  status TEXT NOT NULL DEFAULT 'missing',
  found_at INTEGER,
  found_address TEXT,
  found_lat REAL,
  found_lng REAL,
  found_notes TEXT,
  verified INTEGER DEFAULT 0,
  verified_by TEXT,
  verified_at INTEGER,
  spam INTEGER DEFAULT 0,
  duplicate_of TEXT,
  is_deleted INTEGER DEFAULT 0,
  deleted_by TEXT,
  deleted_at INTEGER,
  deletion_reason TEXT
);

CREATE TABLE IF NOT EXISTS person_notes (
  id TEXT PRIMARY KEY,
  person_id TEXT NOT NULL REFERENCES persons(id),
  created_at INTEGER NOT NULL,
  source TEXT NOT NULL DEFAULT 'web_form',
  author_name TEXT,
  author_contact TEXT,
  author_role TEXT,
  note_status TEXT,
  text TEXT NOT NULL,
  photo_url TEXT,
  location_address TEXT,
  location_lat REAL,
  location_lng REAL,
  found INTEGER DEFAULT 0,
  contact_if_found TEXT
);

CREATE TABLE IF NOT EXISTS rescue_zones (
  id TEXT PRIMARY KEY,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  source TEXT NOT NULL DEFAULT 'web_form',
  reporter_name TEXT,
  reporter_contact TEXT,
  reporter_role TEXT,
  title TEXT NOT NULL,
  description TEXT,
  zone_type TEXT NOT NULL,
  address TEXT,
  lat REAL NOT NULL,
  lng REAL NOT NULL,
  radius_meters INTEGER DEFAULT 50,
  location_notes TEXT,
  urgency TEXT NOT NULL DEFAULT 'high',
  status TEXT NOT NULL DEFAULT 'reported',
  estimated_trapped INTEGER,
  confirmed_trapped INTEGER,
  confirmed_rescued INTEGER,
  confirmed_deceased INTEGER,
  needs_heavy_machinery INTEGER DEFAULT 0,
  needs_canine_unit INTEGER DEFAULT 0,
  needs_medical INTEGER DEFAULT 0,
  needs_structural INTEGER DEFAULT 0,
  needs_blood_type TEXT,
  specific_needs TEXT,
  photo_urls TEXT,
  verified INTEGER DEFAULT 0,
  verified_by TEXT,
  verified_at INTEGER,
  spam INTEGER DEFAULT 0,
  duplicate_of TEXT,
  resolved_at INTEGER,
  resolution_notes TEXT,
  is_deleted INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS help_requests (
  id TEXT PRIMARY KEY,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  source TEXT NOT NULL DEFAULT 'web_form',
  request_type TEXT NOT NULL,
  urgency TEXT NOT NULL DEFAULT 'high',
  ai_urgency TEXT,
  title TEXT,
  description TEXT NOT NULL,
  address TEXT,
  lat REAL,
  lng REAL,
  location_notes TEXT,
  requester_name TEXT,
  requester_contact TEXT NOT NULL,
  for_whom TEXT DEFAULT 'self',
  number_of_people INTEGER DEFAULT 1,
  has_children INTEGER DEFAULT 0,
  has_elderly INTEGER DEFAULT 0,
  has_disabled INTEGER DEFAULT 0,
  has_infants INTEGER DEFAULT 0,
  specific_data TEXT,
  linked_zone_id TEXT REFERENCES rescue_zones(id),
  linked_person_id TEXT REFERENCES persons(id),
  status TEXT NOT NULL DEFAULT 'open',
  assigned_to TEXT,
  assigned_to_id TEXT,
  assigned_at INTEGER,
  fulfilled_at INTEGER,
  fulfillment_notes TEXT,
  verified INTEGER DEFAULT 0,
  spam INTEGER DEFAULT 0,
  duplicate_of TEXT,
  is_deleted INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS volunteers (
  id TEXT PRIMARY KEY,
  registered_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  name TEXT NOT NULL,
  contact TEXT NOT NULL,
  email TEXT,
  country TEXT NOT NULL DEFAULT 'VE',
  city TEXT,
  volunteer_type TEXT NOT NULL DEFAULT 'citizen',
  skills TEXT,
  certifications TEXT,
  has_vehicle INTEGER DEFAULT 0,
  vehicle_type TEXT,
  vehicle_capacity INTEGER,
  has_equipment TEXT,
  org_name TEXT,
  org_type TEXT,
  org_contact TEXT,
  available_from INTEGER,
  available_until INTEGER,
  notes TEXT,
  verified INTEGER DEFAULT 0,
  active INTEGER DEFAULT 1,
  last_seen_at INTEGER,
  is_deleted INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS volunteer_checkins (
  id TEXT PRIMARY KEY,
  volunteer_id TEXT NOT NULL REFERENCES volunteers(id),
  checked_in_at INTEGER NOT NULL,
  checked_out_at INTEGER,
  lat REAL NOT NULL,
  lng REAL NOT NULL,
  accuracy_meters INTEGER,
  address TEXT,
  zone_id TEXT REFERENCES rescue_zones(id),
  zone_name TEXT,
  checkin_status TEXT NOT NULL DEFAULT 'available',
  notes TEXT
);

CREATE TABLE IF NOT EXISTS case_signals (
  id TEXT PRIMARY KEY,
  created_at INTEGER NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  signal_type TEXT NOT NULL,
  contact_hash TEXT,
  ip_hash TEXT,
  note TEXT
);

CREATE TABLE IF NOT EXISTS moderation_log (
  id TEXT PRIMARY KEY,
  created_at INTEGER NOT NULL,
  moderator_id TEXT,
  moderator_name TEXT,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  reason TEXT,
  metadata TEXT
);

CREATE TABLE IF NOT EXISTS pet_reports (
  id TEXT PRIMARY KEY,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  report_kind TEXT NOT NULL,
  pet_name TEXT,
  pet_type TEXT NOT NULL,
  status TEXT,
  description TEXT NOT NULL,
  zone TEXT NOT NULL,
  contact_name TEXT,
  contact_phone TEXT NOT NULL,
  can_foster INTEGER DEFAULT 0,
  photo_url TEXT,
  verified INTEGER DEFAULT 0,
  duplicate_of TEXT,
  is_deleted INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS shelter_reports (
  id TEXT PRIMARY KEY,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  report_kind TEXT NOT NULL,
  title TEXT NOT NULL,
  shelter_type TEXT,
  zone TEXT NOT NULL,
  contact_name TEXT,
  contact_phone TEXT NOT NULL,
  capacity INTEGER,
  group_size INTEGER,
  needs TEXT,
  description TEXT NOT NULL,
  verified INTEGER DEFAULT 0,
  duplicate_of TEXT,
  is_deleted INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS persons_status_idx ON persons(status);
CREATE INDEX IF NOT EXISTS persons_name_idx ON persons(full_name);
CREATE INDEX IF NOT EXISTS persons_location_idx ON persons(last_seen_lat, last_seen_lng);
CREATE INDEX IF NOT EXISTS rescue_zones_status_idx ON rescue_zones(status, urgency);
CREATE INDEX IF NOT EXISTS rescue_zones_location_idx ON rescue_zones(lat, lng);
CREATE INDEX IF NOT EXISTS help_requests_status_idx ON help_requests(status, urgency, request_type);
CREATE INDEX IF NOT EXISTS volunteer_checkins_active_idx ON volunteer_checkins(checked_out_at, checked_in_at);
CREATE INDEX IF NOT EXISTS pet_reports_kind_zone_idx ON pet_reports(report_kind, zone);
CREATE INDEX IF NOT EXISTS shelter_reports_kind_zone_idx ON shelter_reports(report_kind, zone);
